name: 'Fetch CloudFormation Outputs'
description: 'Fetches outputs from all CloudFormation stacks and sets them as environment variables'
inputs:
    AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
    AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
    AWS_REGION:
        description: 'AWS Region'
        required: true

runs:
    using: 'composite'
    steps:
        - name: Configure AWS credentials
          shell: bash
          run: |
              echo "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
              echo "AWS_REGION=${{ inputs.AWS_REGION }}" >> $GITHUB_ENV

        - name: Fetch CFN Outputs for All Stacks
          shell: bash
          run: |
              OUTPUTS=$(aws cloudformation describe-stacks --query "Stacks[].Outputs" --output json)

              echo "=== Raw OUTPUTS ==="
              echo "$OUTPUTS"
              echo "==================="

              declare -A CFN_OUTPUTS

              for row in $(echo "$OUTPUTS" | jq -c ".[] | .[]"); do
                  echo "Processing row: $row"
                  OUTPUT_KEY=$(echo "$row" | jq -r ".OutputKey")
                  OUTPUT_VALUE=$(echo "$row" | jq -r ".OutputValue")

                  OUTPUT_KEY_FORMATTED=$(echo "$OUTPUT_KEY" | tr "[:upper:]" "[:lower:]" | tr -cd "[:alnum:]_")

                  CFN_OUTPUTS[$OUTPUT_KEY_FORMATTED]=$OUTPUT_VALUE
                  echo "Set CFN_OUTPUTS[$OUTPUT_KEY_FORMATTED] = $OUTPUT_VALUE"
              done

              echo "ECS_CLUSTER_NAME=${CFN_OUTPUTS[ecsclustername]}" >> $GITHUB_ENV
              echo "TASK_DEFINITION_ARN=${CFN_OUTPUTS[superusertaskdefinitionarn]}" >> $GITHUB_ENV
              echo "SUBNET_ID=${CFN_OUTPUTS[subnetid]}" >> $GITHUB_ENV
              echo "SECURITY_GROUP_ID=${CFN_OUTPUTS[securitygroupid]}" >> $GITHUB_ENV
