repos:
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: bash -c 'git diff --name-only --cached -- "*.py" | xargs pylint'
            language: system
            types: [python]

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
          - id: bandit
            args: ['-r', 'infra/', 'backend/']
            types: [python]
