repos:
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: bash -c 'git diff --name-only --cached -- "*.py" | xargs pylint'
            language: system
            types: [python]

    - repo: https://github.com/PyCQA/bandit
      rev: '1.8.3'
      hooks:
          - id: bandit
            args: ['-c', 'pyproject.toml', '-r', 'infra/', 'backend/']
            additional_dependencies: ['bandit[toml]']
            types: [python]
