services:
    redis:
        image: redis:latest
        ports:
            - '6379:6379'

    app:
        build: .
        depends_on:
            - redis
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
            - DEBUG=${DEBUG}
            - ENVIRONMENT=${ENVIRONMENT}
            - LOG_LEVEL=${LOG_LEVEL}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - COGNIT_REGION=${COGNIT_REGION}
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        ports:
            - '5000:5000'
