name: Build App

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  pip install pylint pytest bandit -r infra/requirements.txt -r backend/requirements.txt

            - name: Running pylint on backend
              run: |
                  pylint backend/

            - name: Running bandit on backend
              run: |
                  bandit -c pyproject.toml -r backend/

            - name: Running pylint on infra
              run: |
                  pylint infra/

            - name: Running bandit on infra
              run: |
                  bandit -c pyproject.toml -r infra/

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Run ESLint on frontend
              run: |
                  cd frontend
                  npm install
                  npx eslint 'src/*.{ts,tsx}'

            - name: Run Infra Tests
              run: |
                  pytest infra/tests --disable-warnings -q

            - name: Run Backend Tests
              run: |
                  pytest backend/tests --disable-warnings -q
