name: Deploy Stack

on:
    workflow_call:
        inputs:
            stack-name:
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
            AWS_ACCOUNT:
                required: true
    workflow_dispatch:
        inputs:
            stack-name:
                required: true
                type: string

jobs:
    deploy-stack:
        name: Deploy Stack
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.12'

            - name: Install Dependencies
              run: |
                  npm install -g aws-cdk
                  pip install -r backend/requirements.txt
                  pip install aws-cdk-lib constructs

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: CDK Bootstrap (if needed)
              run: cdk bootstrap || echo "Bootstrap already complete"

            - name: Deploy Stack
              run: |
                  export PYTHONPATH="$(pwd):$PYTHONPATH"
                  cdk deploy ${{ github.event.repository.name }}-${{ env.ENVIRONMENT_NAME }}-${{ inputs.stack-name }} --app "python infra/app.py" --require-approval never

              env:
                  PROJECT_NAME: ${{ github.event.repository.name }}
                  ENVIRONMENT_NAME: 'production'
                  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
