name: Deploy CDK Stack and Trigger Schema Deployment

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-core:
        uses: ./.github/workflows/deployCDK.yml
        with:
            stack-name: CoreStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-cluster:
        needs: deploy-core
        uses: ./.github/workflows/deployCDK.yml
        with:
            stack-name: ClusterStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-database:
        needs: deploy-core
        uses: ./.github/workflows/deployCDK.yml
        with:
            stack-name: DatabaseStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-auth:
        needs: deploy-database
        uses: ./.github/workflows/deployCDK.yml
        with:
            stack-name: AuthStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-app:
        needs: [deploy-cluster, deploy-database, deploy-auth]
        uses: ./.github/workflows/deployCDK.yml
        with:
            stack-name: AppStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
