name: Deploy SQL Files

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

jobs:
    fetch-cdk-outputs:
        name: Fetch CDK Outputs
        uses: ./.github/workflows/fetch_cdk_outputs.yml
        with:
            environment: ${{ inputs.environment }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    run-sql-task:
        needs: fetch-cdk-outputs
        runs-on: ubuntu-latest
        steps:
            - name: Run Fargate Task
              run: |
                  echo "ECS Cluster: ${{ env.ecsclustername }}"
                  echo "SQL Task Definition ARN: ${{ env.sqltaskdefarn }}"
                  echo "Subnet ID: ${{ env.subnetid }}"
                  echo "Security Group ID: ${{ env.securitygroupid }}"

                  aws ecs run-task \
                      --cluster ${{ env.ecsclustername }} \
                      --task-definition ${{ env.sqltaskdefarn }}  \
                      --launch-type FARGATE \
                      --network-configuration "awsvpcConfiguration={subnets=[${{ env.subnetid }}],securityGroups=[${{ env.securitygroupid }}],assignPublicIp=ENABLED}"
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
