name: Deploy SQL Files

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

jobs:
    fetch-cdk-outputs:
        name: Fetch CDK Outputs
        uses: ./.github/workflows/fetch_cdk_outputs.yml
        with:
            environment: ${{ inputs.environment }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    run-sql-task:
        needs: fetch-cdk-outputs
        runs-on: ubuntu-latest
        steps:
            - name: Run Fargate Task
              run: |
                  echo "ECS Cluster: $ECS_CLUSTER_NAME"
                  echo "SQL Task Definition ARN: $SQL_TASK_DEFINITION_ARN"
                  echo "Subnet ID: $SUBNET_ID"
                  echo "Security Group ID: $SECURITY_GROUP_ID"

                  aws ecs run-task \
                      --cluster $ECS_CLUSTER_NAME \
                      --task-definition $SQL_TASK_DEFINITION_ARN  \
                      --launch-type FARGATE \
                      --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=ENABLED}"
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  ECS_CLUSTER_NAME: ${{ needs.fetch-cdk-outputs.outputs.ecsclustername }}
                  SQL_TASK_DEFINITION_ARN: ${{ needs.fetch-cdk-outputs.outputs.sqltaskdefarn }}
                  SUBNET_ID: ${{ needs.fetch-cdk-outputs.outputs.subnetid }}
                  SECURITY_GROUP_ID: ${{ needs.fetch-cdk-outputs.outputs.securitygroupid }}
