name: Deploy Super User

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            superuser_email:
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

jobs:
    fetch-cdk-outputs:
        name: Fetch CDK Outputs
        uses: ./.github/workflows/fetch_cdk_outputs.yml
        with:
            environment: ${{ inputs.environment }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    run-superuser-task:
        needs: fetch-cdk-outputs
        runs-on: ubuntu-latest
        steps:
            - name: Run Fargate Task
              # CDK Output keys are forced to "lowercase smash case"
              run: |
                  aws ecs run-task \
                      --cluster ${{ needs.fetch-cdk-outputs.outputs.ecsclustername }} \
                      --task-definition ${{ needs.fetch-cdk-outputs.outputs.superusertaskdefarn }} \
                      --launch-type FARGATE \
                      --network-configuration "awsvpcConfiguration={subnets=[${{ needs.fetch-cdk-outputs.outputs.subnetid }}],securityGroups=[${{ needs.fetch-cdk-outputs.outputs.securitygroupid }}],assignPublicIp=ENABLED}" \
                      --overrides '{"containerOverrides":[{"name":"SuperuserContainer","environment":[{"name":"SUPERUSER_EMAIL","value":"${{ inputs.superuser_email }}"}]}]}'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
