name: Deploy App

on:
    workflow_dispatch:
        inputs:
            stack-name:
                description: 'Comma-separated list of stacks to deploy (default: Empty to run all)'
                required: false
                default: ''

jobs:
    deploy-network-stack:
        uses: ./.github/workflows/deployStack.yml
        with:
            stack-name: NetworkStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-user-stack:
        uses: ./.github/workflows/deployStack.yml
        with:
            stack-name: UserStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-compute-stack:
        needs: deploy-network-stack
        uses: ./.github/workflows/deployStack.yml
        with:
            stack-name: ComputeStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-storage-stack:
        needs: deploy-network-stack
        uses: ./.github/workflows/deployStack.yml
        with:
            stack-name: StorageStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-runtime-stack:
        needs: [deploy-compute-stack, deploy-storage-stack]
        uses: ./.github/workflows/deployReactStack.yml
        with:
            stack-name: RuntimeStack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    create-superuser:
        needs: deploy-user-stack
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Invoke Lambda to create Cognito user
              run: |
                  aws lambda invoke \
                  --function-name create-superuser-lambda \
                  --payload '{"email": "${{ vars.SUPERUSER_EMAIL}}"}' \
                  response.json \
                  --cli-binary-format raw-in-base64-out
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
