name: Deploy Super User

on:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
    workflow_dispatch:

jobs:
    run-superuser-task:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Fetch CFN Outputs
              uses: ./.github/actions/fetch_cfn_outputs
              with:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}

            - name: Run ECS Task
              run: |
                  aws ecs run-task \
                    --cluster "$ECS_CLUSTER_NAME" \
                    --task-definition "$SUPER_USER_TASK_DEFINITION_ARN" \
                    --launch-type FARGATE \
                    --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=ENABLED}"
                    --overrides '{
                        "containerOverrides": [{
                            "name": "superuser-container",
                            "environment": [
                                {"name": "PROJECT_NAME", "value": "'${{ github.repository }}'"},
                                {"name": "SUPERUSER_EMAIL", "value": "'${{ secrets.SUPERUSER_EMAIL }}'"}
                            ]
                        }]
                    }'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
