name: Deployment Orchestration

on:
    workflow_dispatch:
        inputs:
            stack-name:
                description: 'Comma-separated list of jobs to run (default: Empty to run all)'
                required: false
                default: ''

jobs:
    deploy-app:
        if: ${{ inputs.stack-name == '' }}
        name: Deploy All Stacks and Stand up the Application Environment
        uses: ./.github/workflows/deploy_app.yml
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-network-stack:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-network-stack') }}
        name: Deploy Network Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: network-stack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-user-stack:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-user-stack') }}
        name: Deploy User Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: user-stack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-superuser:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-superuser') }}
        name: Deploy Super User
        uses: ./.github/workflows/deploy_superuser.yml
        with:
            environment: production
            superuser_email: ${{ vars.SUPERUSER_EMAIL }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-compute-stack:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-compute-stack') }}
        name: Deploy Compute Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: compute-stack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-storage-stack:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-storage-stack') }}
        name: Deploy Storage Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: storage-stack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-sql-files:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-sql-files') }}
        name: Deploy SQL Files
        uses: ./.github/workflows/deploy_sql.yml
        with:
            environment: production
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-runtime-stack:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-runtime-stack') }}
        name: Deploy Runtime Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: runtime-stack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-environment-setup-stack:
        if: ${{ inputs.stack-name != '' && contains(inputs.stack-name, 'deploy-environment-setup-stack') }}
        name: Deploy Environment Setup Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: environment-setup-stack
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
