name: Deploy App

on:
    workflow_dispatch:
        inputs:
            ENVIRONMENT_NAME:
                type: string
                default: 'production'

permissions:
    id-token: write
    contents: read

jobs:
    deploy-user-management-stack:
        uses: ./.github/workflows/deploy_stack.yml
        name: Deploy User Management Stack
        with:
            stack-name: user-management
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    deploy-network-stack:
        uses: ./.github/workflows/deploy_stack.yml
        name: Deploy Network Stack
        with:
            stack-name: network
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    deploy-compute-stack:
        needs: deploy-network-stack
        name: Deploy Compute Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: compute
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    deploy-storage-stack:
        needs: deploy-network-stack
        name: Deploy Storage Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: storage
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    deploy-runtime-stack:
        needs: [deploy-compute-stack, deploy-storage-stack]
        name: Deploy Runtime Stack
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: runtime
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    deploy-deployment-stack:
        name: Deploy Deployment Stack
        needs: [deploy-storage-stack, deploy-user-management-stack]
        uses: ./.github/workflows/deploy_stack.yml
        with:
            stack-name: deployment
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    deploy-sql-files:
        name: Deploy SQL Files
        needs: [deploy-deployment-stack, deploy-storage-stack]
        uses: ./.github/workflows/deploy_sql.yml
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    deploy-superuser:
        name: Deploy Super User
        needs:
            [
                deploy-deployment-stack,
                deploy-user-management-stack,
                deploy-storage-stack,
            ]
        uses: ./.github/workflows/deploy_superuser.yml
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

    destroy-deployment-stack:
        name: Destroy Deployment Stack
        needs: [deploy-deployment-stack, deploy-sql-files, deploy-superuser]
        uses: ./.github/workflows/destroy_stack.yml
        with:
            stack-name: deployment
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    stop-rds:
        name: Stop RDS Instance
        needs: [deploy-deployment-stack, deploy-sql-files, deploy-superuser]
        uses: ./.github/workflows/stop_rds.yml
        permissions:
            id-token: write
            contents: read
        with:
            ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
