name: Fetch CDK Outputs

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

jobs:
    fetch-outputs:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch CDK Outputs Dynamically
              id: fetch
              run: |
                  STACK_NAME=${{ github.event.repository.name }}-environment-setup-stack-${{ inputs.environment }}
                  OUTPUTS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs" --output json)

                  # Loop through each output and dynamically set them
                  for row in $(echo "$OUTPUTS" | jq -c '.[]'); do
                      OUTPUT_KEY=$(echo "$row" | jq -r '.OutputKey')
                      OUTPUT_VALUE=$(echo "$row" | jq -r '.OutputValue')
                      # Convert key to lowercase and replace invalid characters for GitHub Actions outputs
                      OUTPUT_KEY_FORMATTED=$(echo "$OUTPUT_KEY" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_')
                      echo "$OUTPUT_KEY_FORMATTED=$OUTPUT_VALUE" >> $GITHUB_ENV
                  done
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
