name: 'Invoke Lambda'

on:
    workflow_call:
        inputs:
            lambda_name:
                description: 'The name of the Lambda function to invoke'
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

jobs:
    invoke:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Invoke Lambda
              run: |
                  echo "Invoking Lambda: ${{ inputs.lambda_name }}"
                  aws lambda invoke \
                    --function-name "${{ inputs.lambda_name }}" \
                    --payload '{}' \
                    response.json
                  cat response.json
