name: Push To S3

on:
    workflow_dispatch:

jobs:
    push-to-s3:
        name: Push Assets to S3
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Sync assets to S3
              run: aws s3 sync infra/assets s3://${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT_NAME }}-bucket --delete
              env:
                  PROJECT_NAME: ${{ github.event.repository.name }}
                  ENVIRONMENT_NAME: 'production'
