name: Stop RDS

on:
    workflow_dispatch:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true

permissions:
    id-token: write
    contents: read

jobs:
    stop-rds:
        runs-on: ubuntu-latest

        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::123456789012:role/github-ci-role
                  aws-region: us-east-1

            - name: Fetch CFN Outputs
              uses: ./.github/actions/fetch_cfn_outputs
              with:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}

            - name: Stop RDS instance
              run: |
                  aws ssm start-automation-execution \
                    --document-name AWS-StopRdsInstance \
                    --parameters "InstanceId=$RDS_INSTANCE_ARN"
